


# Generated by Django 4.1.1 on 2022-09-12 15:37



from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_rename_institutions_user_institution"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="about",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="degree",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("Regular", "Regular"),
                    ("Admin", "Admin"),
                    ("Reviewer", "Reviewer"),
                ],
                default="Regular",
                max_length=15,
            ),
        ),
    ]
