# Generated by Django 4.1.1 on 2022-09-08 14:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="feedbacks",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("feedback", models.CharField(max_length=200)),
                ("rate", models.IntegerField()),
            ],
        ),
    ]
