# Generated by Django 4.1.1 on 2022-09-12 13:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_alter_work_created_at_alter_work_summary_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feedbacks', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='feedbacks',
            new_name='Feedback',
        ),
    ]
