# Generated by Django 4.1.1 on 2022-09-12 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0003_rename_feedbacks_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='rate',
            field=models.FloatField(),
        ),
    ]
