# Generated by Django 4.1.1 on 2022-09-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("works", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="work",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="work",
            name="summary",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="work",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
